#ifndef SCENE_GAME_OVER_INFORMATION_H_
#define SCENE_GAME_OVER_INFORMATION_H_





//ƒƒjƒ…[‚©‚çŽó‚¯Žæ‚Á‚½î•ñ‚ðÆ‡‚·‚éindex.
enum enINFORMATION_INDEX : char
{
	enINFORMATION_INDEX_GAME_OVER = 0,
	enINFORMATION_INDEX_CONTINUE,
	enINFORMATION_INDEX_ASSEMBLE,
				 
	enINFORMATION_INDEX_size
};



#endif//#ifndef SCENE_GAME_OVER_INFORMATION_H_