#ifndef SCENE_MISSION_INFORMATION_H_
#define SCENE_MISSION_INFORMATION_H_

enum enINFORMATION_INDEX : char
{
	enINFORMATION_INDEX_WINDOW_CLOSE = 0,	//ポーズ解除.
	enINFORMATION_INDEX_MISSION_FAILED,		//ミッション放棄.

	enINFORMATION_INDEX_size
};

#endif//#ifndef SCENE_MISSION_INFORMATION_H_