#ifndef SCENE_TITLE_INFORMATION_H_
#define SCENE_TITLE_INFORMATION_H_



//ƒƒjƒ…[‚©‚çŽó‚¯Žæ‚Á‚½î•ñ‚ðÆ‡‚·‚é.
enum enINFORMATION_INDEX : char
{
	enINFORMATION_INDEX_GAME_END = 0,
	enINFORMATION_INDEX_NEXT_SCENE,
	enINFORMATION_INDEX_CLOSE_MENU,

	enINFORMATION_INDEX_size
};

#endif//#ifndef SCENE_TITLE_INFORMATION_H_