#ifndef SCENE_ASSEMBLE_INFORMATION_H_
#define SCENE_ASSEMBLE_INFORMATION_H_


//âπÇÃà¯êî.
enum enBGM : int
{
	enBGM_RENGOKU0 = 0,
	enBGM_MAOU0,
	enBGM_MAOU2,
};

enum enSE : int
{
	enSE_CURSOL_MOVE = 0,
	enSE_ENTER,
	enSE_EXIT,
	enSE_MISSION_START,
	enSE_WIN_APP,
	enSE_WIN_DISAPP,
};


//ÉÅÉjÉÖÅ[Ç©ÇÁéÛÇØéÊÇ¡ÇΩèÓïÒÇè∆çáÇ∑ÇÈ.
enum enINFORMATION_INDEX : char
{
	enINFORMATION_INDEX_GO_TITLE = 0,
	enINFORMATION_INDEX_GO_MISSION,
	enINFORMATION_INDEX_CLOSE_WINDOW,

	enINFORMATION_INDEX_COLOR_1_R_INCREMENT,
	enINFORMATION_INDEX_COLOR_1_R_DECREMENT,
	enINFORMATION_INDEX_COLOR_1_G_INCREMENT,
	enINFORMATION_INDEX_COLOR_1_G_DECREMENT,
	enINFORMATION_INDEX_COLOR_1_B_INCREMENT,
	enINFORMATION_INDEX_COLOR_1_B_DECREMENT,
							   
	enINFORMATION_INDEX_COLOR_2_R_INCREMENT,
	enINFORMATION_INDEX_COLOR_2_R_DECREMENT,
	enINFORMATION_INDEX_COLOR_2_G_INCREMENT,
	enINFORMATION_INDEX_COLOR_2_G_DECREMENT,
	enINFORMATION_INDEX_COLOR_2_B_INCREMENT,
	enINFORMATION_INDEX_COLOR_2_B_DECREMENT,

	enINFORMATION_INDEX_size
};



#endif//#ifndef SCENE_ASSEMBLE_INFORMATION_H_